/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weatherstation.panels;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import weatherstation.MainPanelDriver;
import static weatherstation.MainPanelDriver.air;
import static weatherstation.MainPanelDriver.dateTime;
import static weatherstation.WeatherStation.cards;
import weatherstation.WeatherStation;
import static weatherstation.WeatherStation.frame;
import static weatherstation.panels.MainDashboardPanel.topLabel;
import weatherstation.utilities.CollectInput;

/**
 *
 * @author David
 */
public class PostcodeSelectPanel extends javax.swing.JPanel {

    /**
     * Creates new form PostcodeSelectPanel
     */
    public PostcodeSelectPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this codeUp. The content of this method is always
 regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        goButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 86, 150));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(650, 600));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(236, 244, 250));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Australian Weather Station");

        jTextField1.setBackground(new java.awt.Color(236, 244, 250));
        jTextField1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Postcode: eg. 3066");
        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        goButton.setBackground(new java.awt.Color(0, 86, 150));
        goButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        goButton.setForeground(new java.awt.Color(255, 255, 255));
        goButton.setText("GO");
        goButton.setFocusPainted(false);
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please Enter your Postcode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(goButton, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addGap(177, 177, 177))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
        WeatherStation.conditionsTimePanel.add(MainDashboardPanel.label[topLabel]);
        WeatherStation.conditionsTimePanel.add(MainDashboardPanel.label2[dateTime]);
        WeatherStation.frame.getContentPane().add(WeatherStation.navigationPanel, BorderLayout.SOUTH);
        
        CardLayout cl = (CardLayout)(cards.getLayout());
        cl.show(cards, "Main");
        WeatherStation.button[WeatherStation.NAVIGATION_BUTTON].grabFocus();
        WeatherStation.button[WeatherStation.NAVIGATION_BUTTON].requestFocus();
        WeatherStation.button[WeatherStation.NAVIGATION_BUTTON].setText("Graph");
        String postCode = jTextField1.getText();
        int codeUp = Integer.parseInt(postCode);
        int codeDown = codeUp;
        CollectInput.getPostcodeInfo(postCode);
        while(CollectInput.validWMO.size() == 0){
            codeUp++;
            CollectInput.getPostcodeInfo(String.valueOf(codeUp));
            codeDown--;
            CollectInput.getPostcodeInfo(String.valueOf(codeDown));
        }
        try {
            MainPanelDriver.initializeArrays();
        } catch (IOException ex) {
            
        }
        if(CollectInput.stationName.length() > maxStringLength){
            CollectInput.stationName = CollectInput.stationName.substring(0, maxStringLength);
        }
        MainDashboardPanel.label[topLabel].setText(CollectInput.stationName.toString() + " at ");
        System.out.println("next");
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        WeatherStation.conditionsTimePanel.add(MainDashboardPanel.label[topLabel]);
        WeatherStation.conditionsTimePanel.add(MainDashboardPanel.label2[dateTime]);
        WeatherStation.frame.getContentPane().add(WeatherStation.navigationPanel, BorderLayout.SOUTH);
        
        CardLayout cl = (CardLayout)(cards.getLayout());
        cl.show(cards, "Main");
        WeatherStation.button[WeatherStation.NAVIGATION_BUTTON].grabFocus();
        WeatherStation.button[WeatherStation.NAVIGATION_BUTTON].requestFocus();
        WeatherStation.button[WeatherStation.NAVIGATION_BUTTON].setText("Graph");
        String postCode = jTextField1.getText();
        int codeUp = Integer.parseInt(postCode);
        int codeDown = codeUp;
        CollectInput.getPostcodeInfo(postCode);
        while(CollectInput.validWMO.size() == 0){
            codeUp++;
            CollectInput.getPostcodeInfo(String.valueOf(codeUp));
            codeDown--;
            CollectInput.getPostcodeInfo(String.valueOf(codeDown));
        }
        try {
            MainPanelDriver.initializeArrays();
        } catch (IOException ex) {
            
        }
        if(CollectInput.stationName.length() > maxStringLength){
            CollectInput.stationName = CollectInput.stationName.substring(0, maxStringLength);
        }
        MainDashboardPanel.label[topLabel].setText(CollectInput.stationName.toString() + " at ");
        System.out.println("next");
    }//GEN-LAST:event_goButtonActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
        Point p = frame.getLocation();
        frame.setLocation(p.x + evt.getX() - point.x,
                p.y + evt.getY() - point.y);
            
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    Point point = new Point();
    int maxStringLength = 20;
}
